### ISSUE TITLE
Turbolinks 5

### ISSUE THREAD

**Issue by Huibin** [frenzyapp/turbolinks#11]
Hi 

Turbolinks 5 kills 3. Any plans to update?

Actually we're planning do a hybrid mobile app, and thinking native+turbolinks is better than js+phonegap. But it needs our Laravel web app implements Turbolinks. 

Thank you guys.

**Comment by tortuetorche** [comment]
Hi Huibin,

I ported Turbolinks 5, but I didn't send a pull request on this project yet.
Because I waiting for this pull request https://github.com/helthe/Turbolinks/pull/10 to be merged.

You can grab the code here: https://github.com/efficiently/turbolinks/tree/turbo5
And if you want a demo, look here: https://github.com/efficiently/laravel_larasset_app/tree/turbo5-l5.1
The `composer.json` of this demo can be very useful: https://github.com/efficiently/laravel_larasset_app/blob/turbo5-l5.1/composer.json#L7

Cheers,
Tortue Torche

**Comment by Huibin** [comment]
Cool, I will check that.

Thank you Tortue
